### ISSUE TITLE
Erro na execução do "make engine-company-tax-regime"

### ISSUE THREAD

**Issue by filipecarneiro** [libercapital/dados_publicos_cnpj_receita_federal#25]
$ make engine-company-tax-regime

```
docker-compose up -d
postgres is up-to-date
Starting app ... done

compose-up run app container & [ENGINE COMPANY TAX REGIME]
Creating cnpj_app_run ... done
creating dict files url
ref date will be: '2024-05-24' with 37 out of 37 (100.0%)
Found pk on: 'rf_company_tax_regime'
dropping pk.... ['alter table rf_company_tax_regime drop constraint rf_company_tax_regime_pkey']
dropped
Delete 'ix_rf_company_tax_regime_cnpj' from 'rf_company_tax_regime'
Delete 'ix_rf_company_tax_regime_cnpj_root' from 'rf_company_tax_regime'
[ 1/9] Getting file Imunes e isentas.csv
Traceback (most recent call last):
  File "src/engine/company_tax_regime.py", line 74, in <module>
    CompanyTaxRegime().execute()
  File "src/engine/company_tax_regime.py", line 26, in execute
    self.parse_all_files()
  File "/app/src/engine/core.py", line 91, in parse_all_files
    self.parse_file(file=file)
  File "src/engine/company_tax_regime.py", line 50, in parse_file
    for _df in pd.read_csv(**dict_args_read_csv):
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1624, in __next__
    return self.get_chunk()
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1733, in get_chunk
    return self.read(nrows=size)
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/root/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 824, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 889, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 951, in pandas._libs.parsers.TextReader._convert_column_data
pandas.errors.ParserError: Too many columns specified: expected 5 and found 1
ERROR: 1
make: *** [Makefile:152: engine-company-tax-regime] Error 1
```

**Comment by alexmdcampo** [comment]
o mesmo aqui

 Too many columns specified: expected 5 and found 1
ERROR: 1

**Comment by alexmdcampo** [comment]
@filipecarneiro 

consegui identificar o problema, os aqruivos abaixo estão com sepração de ; e o esperado é ,

ajuste a speração e ira funcionar (vc pode incluir apos o ajuste diretamente na unziped)
Imunes e isentas
Lucro Presumido 2017  2018 2019 2020 2021 2022

após o ajuste passou todos arquivos
