### ISSUE TITLE
erro no make io-download-and-unzip

### ISSUE THREAD

**Issue by antonio24073** [libercapital/dados_publicos_cnpj_receita_federal#27]
oi tudo bem? 

Pois é tentei em 2 máquinas já e dá o mesmo erro. Não sei se mudou alguma coisa no link que faz o scraper.

```bash
$ make io-download-and-unzip
---------------------------------------
docker-compose up -d
WARN[0000] /home/antonio/Documents/projects/dados_publicos_cnpj_receita_federal/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([dados_publicos_cnpj_receita_federal_app_run_94b41aa3b472]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 2/2
 ✔ Container postgres  Running                                                                                                                                0.0s 
 ✔ Container app       Started                                                                                                                                0.4s 

compose-up run app container & [DOWNLOAD]
WARN[0000] /home/antonio/Documents/projects/dados_publicos_cnpj_receita_federal/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] Found orphan containers ([dados_publicos_cnpj_receita_federal_app_run_94b41aa3b472]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Creating 1/0
 ✔ Container postgres  Running                                                                                                                                0.0s 
creating dict files url
Traceback (most recent call last):
  File "src/io/download.py", line 94, in <module>
    main()
  File "src/io/download.py", line 17, in main
    dict_files_dict = get_files_dict()
  File "/app/src/io/get_files_dict.py", line 19, in main
    ref_date = get_last_ref_date()
  File "/app/src/io/get_last_ref_date.py", line 36, in main
    ref_date, occurences = Counter(list_last_modified_at).most_common(1)[0]
IndexError: list index out of range
make: *** [Makefile:132: io-download-and-unzip] Error 1

```

Se puder responder o problema, mesmo antes de alterar, já para eu poder saber se espero ajustar. Eu até ajudaria a fazer porem  comecei agora com esse projeto e não sei bem o que é esperado na extração de dados para que o parser funcione.

Não esqueça de responder.
Até mais.
Obrigado por manter esse projeto.

**Comment by Robso-creator** [comment]
Oi @antonio24073 

A receita mudou a estrutura do site, o que causava o erro no `get_last_ref_date.py`. O código precisa de algumas alterações para que volte a funcionar.

Na branch `fix_get_data` estão as mudanças necessárias. Em breve será mergiado na main.

Obrigado pelo tempo

**Comment by antonio24073** [comment]
oi td bem? 
eu estava aguardando colocar na main, então resolvi testar a gbranch fix_get_data.. porem nao está funcionando ainda.

```
/app/src/io/get_last_ref_date.py:21: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(page.text, 'html.parser')
Traceback (most recent call last):
  File "src/io/download.py", line 94, in <module>
    main()
  File "src/io/download.py", line 17, in main
    dict_files_dict = get_files_dict()
  File "/app/src/io/get_files_dict.py", line 19, in main
    ref_date = get_last_ref_date()
  File "/app/src/io/get_last_ref_date.py", line 24, in main
    rows = table.find_all('tr')
AttributeError: 'NoneType' object has no attribute 'find_all'
make: *** [Makefile:132: io-download-and-unzip] Error 1
```

**Comment by antonio24073** [comment]
Tenho a impressão que agora mudou tudo

**Comment by Robso-creator** [comment]
A estrutura do site da receita mudou, por isso teve alteração em como pegar os arquivos, tanto na `get_last_ref_date.py` quanto na `get_files_dict.py`

pela mensagem de erro, é devido a mudança de URL feita pela receita federal. Acabei de dar push na branch com alterações.

![image](https://github.com/user-attachments/assets/f906d69f-bb63-4ff6-8ebd-8393146d3a19)

**Comment by Robso-creator** [comment]
acabei de fazer o merge na branch main

só dar git pull e ser feliz :D
